services:
  backend:
    build: .
    container_name: backend-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - prototype-network
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.1
    container_name: es01
    environment:
      - ES_PORT=localhost:9200
      - ELASTIC_PASSWORD=password1234@
      - STACK_VERSION=9.3.1
      - node_name=es01
      - cluster_name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - prototype-network
    healthcheck:
      test: ["CMD", "curl", "-XGET", "http://localhost:9200/_cluster/health?pretty"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  elastic_data:

networks:
  prototype-network:
    driver: bridge